### ISSUE TITLE
Scheduler should be able to communicate over SSL 

### ISSUE THREAD

**Issue by mcoffin** [tobilg/mesos-framework#11]
Unless I'm wrong, I don't currently see a way to tell the scheduler to use SSL to communicate with the master.

For ease of integration with existing frameworks, it might be prudent to even look in the `LIBPRROCESS_SSL_` environment variables to look for SSL configuration options.

**Comment by tobilg** [comment]
Can you please elaborate a bit? Do you mean that the scheduler should be communicate via `https` with the masters? Apart from that, are there further requirements?

**Comment by mcoffin** [comment]
> are there further requirements?

Not really, but ideally, being able to specify ssl options (cert file / key file / etc.) would certainly be necessary to fit use cases other than mine.

**Comment by tobilg** [comment]
I'll probably not be able to work on this in the short-term. PRs are warmly welcomed though. Thanks in advance.

**Comment by mcoffin** [comment]
> PRs are warmly welcomed though

I primarily opened this as a way to track my work ;)

**Comment by tobilg** [comment]
This is great news! If you could also include tests that would be fantastic. Thanks!

**Comment by tobilg** [comment]
Any updates @mcoffin? Or is this no longer relevant?

**Comment by mcoffin** [comment]
Wound up building [`purescript-mesos`](https://github.com/mcoffin/purescript-mesos) as an alternative. Definitely not mature at all but it does what I need.

**Comment by mcoffin** [comment]
Well, I'd say this should still probably be on the roadmap for this project though. With the HTTP apis we're going to see far more mesos clusters using SSL+authentication for security I'd expect. Your choice though, but I won't have time to put in to it right now.

**Comment by tobilg** [comment]
I have no time to work on it either. As there doesn't seem to be much interest in having SSL support, I'll suggest you open it again once it's relevant for you.
