### ISSUE TITLE
Bridge networking

### ISSUE THREAD

**Issue by charlessolar** [tobilg/mesos-framework#16]
Using the boilerplate app you provided I've been playing with mesos framework (very easy to setup thanks!)
But I think there is an issue when trying to use BRIDGE networking.

Here: https://github.com/tobilg/mesos-framework/blob/master/lib/schedulerHandlers.js#L229

The `if == "BRIDGE"` doesn't work because the field is an enum not a string.  So if you define a container like

```
var containerInfo = new Mesos.ContainerInfo(
        Mesos.ContainerInfo.Type.DOCKER, // Type
        null, // Volumes
        null, // Hostname
        new Mesos.ContainerInfo.DockerInfo(
            process.env["TASK" + taskTypeId + "_IMAGE"], // Image
            Mesos.ContainerInfo.DockerInfo.Network.BRIDGE, // Network
            new Mesos.ContainerInfo.DockerInfo.PortMappings(

            ), // PortMappings
            helpers.checkBooleanString(process.env["TASK" + taskTypeId + "_CONTAINER_PRIVILEGED"], false), // Privileged
            process.env["TASK" + taskTypeId + "_CONTAINER_PARAMS"]
                ? JSON.parse(process.env["TASK" + taskTypeId + "_CONTAINER_PARAMS"])
                : null,  // Parameters
            true, // forcePullImage
            null   // Volume Driver
        )
    );
```

It won't work.  Changing the line in schedulehandlers.js to

`if == mesos.ContainerInfo.DockerInfo.Network.BRIDGE` fixed the issue for me.

**Comment by tobilg** [comment]
This is fixed on master: https://github.com/tobilg/mesos-framework/commit/9c249a33c63bbb766f0505cdb199fcff04a4a292 Thanks for the hint!
