### ISSUE TITLE
requireFrom causing issues

### ISSUE THREAD

**Issue by charlessolar** [tobilg/mesos-framework#18]
Going through updating old packages and finding I'm unable to use your latest v0.7.0 because requireFrom is having issues finding the right folder.

You can see the issue if you use your boilerplate https://github.com/tobilg/mesos-framework-boilerplate and update the `mesos-framework` to v0.7.0

`npm start` will yield:

```
> node index.js

module.js:442
    throw err;
    ^

Error: Cannot find module '/usr/local/mesos-framework-boilerplate/lib/mesos'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at requireModule (/usr/local/mesos-framework-boilerplate/node_modules/requirefrom/index.js:24:10)
    at Object.<anonymous> (/usr/local/mesos-framework-boilerplate/node_modules/mesos-framework/lib/schedulerHandlers.js:5:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by charlessolar** [comment]
Workaround for now is to shortcut the `require()` by copying `node_modules/mesos-framework` into the root directory.

add the addition RUN command like so
```
# Setup of the application
RUN npm install --silent && \
    npm install bower -g && \
    bower install --allow-root

RUN cp -r node_modules/mesos-framework ./mesos-framework
CMD ["sh", "./get_creds.sh"]

``` 
into the Dockerfile

**Comment by tobilg** [comment]
Thanks for reporting. I think this issue belongs to the https://github.com/tobilg/mesos-framework-boilerplate project (which wasn’t updated nor tested with the 0.7.0 version yet).

**Comment by charlessolar** [comment]
Hm - well it could be the boilerplate project is not importing correctly.  Its just doing 

```
Mesos = require("mesos-framework").Mesos.getMesos();
``` 

which fails.  

Its been a long time since I did anything with require so I'm not familiar with the specific issue relating to this line and requirefrom - but if that shouldn't work anymore then I'd agree the issue belongs there.

**Edit**
Its very likely the issue is the project is just doing `npm start` instead of building a slug and solidifying dependencies now that I think about it
